// File generated by FlutterFire CLI.
// This file should be generated using the 'flutterfire configure' command.
// Note: This is a placeholder. In a real project, this would be generated by the FlutterFire CLI.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default FirebaseOptions for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKSppYq8qCElO8dhilm1vfQWCb9s3L2dI',
    appId: '1:312703723408:android:46d89139e349ee4cbe7515',
    messagingSenderId: '312703723408',
    projectId: 'comet-218a7',
    storageBucket: 'comet-218a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKSppYq8qCElO8dhilm1vfQWCb9s3L2dI',
    appId: '1:312703723408:ios:edbe772b0044de7bbe7515',
    messagingSenderId: '312703723408',
    projectId: 'comet-218a7',
    storageBucket: 'comet-218a7.firebasestorage.app',
    iosClientId: '312703723408-fsdr9tqda3p7q7i6n2598b0pti10cdh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.comet',
  );
}
